[package]
name = "glow-with-glutin"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.28"
smithay-client-toolkit = "0.20.0"
wayland-client = "0.31.11"

glow = "0.14"
glutin = "0.32"
raw-window-handle = "0.6.2"
